name: Sync README.md to Docker Hub

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: Log level     
            required: false
            default: warning
    push:
        branches:
            - main

jobs:
    sync-readme:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        - 
            name: Docker Hub README & description sync
            uses: bemble/sync-readme@v1.0.0
            with:
                user: ${{ secrets.DOCKERHUB_USERNAME }}
                pass: ${{ secrets.DOCKERHUB_PASSWORD }}
                slug: ${{ secrets.DOCKERHUB_USERNAME }}/upmpdcli
                readme: ./README.md
                description: UPnP Audio Media Renderer based on MPD
                
