name: Sync README.md to Docker Hub

on:
  push:
    branches:
      - 'main'
    paths:
      - README.md
      - .github/workflows/sync-description.yml
  pull_request:
    branches:
      - 'main'
    paths:
      - README.md
      - .github/workflows/sync-description.yml

jobs:
    # This workflow contains a single job called "sync-readme"
    sync-readme:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Set environment variables
        env:
          DOCKERHUB_SLUG: ${{secrets.DOCKERHUB_USERNAME}}/upmpdcli
          
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Github action to get branch or tag information without the /ref/* prefix
          - name: Checkout
            uses: actions/checkout@v3

            # Github action to sync description files to docker hub
          - name: Docker Hub README & description sync
            uses: peter-evans/dockerhub-description@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
                repository: ${{ env.DOCKERHUB_SLUG }}
                readme-filepath: ./README.md
                short-description: UPnP Audio Media Renderer based on MPD
                        
